// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"detail-table":{"path":"detail-table","id":"detail-table","parentId":"@@/global-layout"},"form-dialog":{"path":"form-dialog","id":"form-dialog","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'detail-table': React.lazy(() => import(/* webpackChunkName: "src__pages__detail-table" */'../../../src/pages/detail-table.tsx')),
'form-dialog': React.lazy(() => import(/* webpackChunkName: "src__pages__form-dialog" */'../../../src/pages/form-dialog.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/congger_macmini/Documents/Jagger/test/src/layouts/index.tsx')),
},
  };
}
